/**
 * Exercise — cells 20, 22, 28 and 29.
 *
 * Six recipes that call the published assets through the gateway the way a
 * consumer would: two MCP handshakes, two A2A calls, one Agent Framework
 * client, and one direct tool invocation.
 */

import { step, createExecutionPlan } from '../../core/plan.mjs';
import { agentCardUrl, agentEndpoint, mcpEndpoint } from '../../core/endpoints.mjs';
import { mcpCallStep, mcpHandshakeExpectations, mcpInitializeStep } from '../../core/mcp.mjs';
import { secretRef } from '../../core/secrets.mjs';
import { LINKS } from '../profiles.mjs';

const FAHRENHEIT_CITIES = ['Seattle', 'New York City', 'Los Angeles'];

function endpointFieldsFor({ pathDefault, assetType, label, docLink }) {
  return [
    {
      name: 'assetPath',
      label: `${label} path`,
      type: 'string',
      classification: 'sample-default',
      width: 'short',
      default: pathDefault,
      help:
        assetType === 'mcp-from-api'
          ? 'Used only when no deployed endpoint is recorded. An API→MCP server is served at `{gateway}/mcp/{path}/mcp`.'
          : 'Used only when no deployed endpoint is recorded. A native MCP server is served at `{gateway}/mcp/{path}` with no trailing `/mcp`.',
      howToObtain: 'Fixed by the notebook (cell 14). Must match the published asset`s `path`.',
      links: [docLink],
      notebookRef: 'cell 14 asset `path`',
    },
    {
      name: 'deployedEndpoint',
      label: 'Deployed endpoint (authoritative)',
      type: 'url',
      classification: 'derived',
      width: 'long',
      default: '',
      derivedFrom: 'Produced by Publish and grant › Publish the three assets (`publishedAssets[].endpoint`).',
      help: 'The endpoint the deployment reported. When set it wins over anything composed from the path, exactly as the notebook prefers it.',
      howToObtain: 'Copy it from the publish deployment`s `publishedAssets` output.',
      links: [LINKS.apimMcpOverview],
      notebookRef: 'cell 20 `published_by_name[...]["endpoint"]`',
    },
  ];
}

function mcpDiscoveryPrerequisites(extra = []) {
  return [
    {
      id: 'assets-published',
      title: 'The asset is published',
      detail: 'The MCP server only exists once the publish contract has been deployed.',
      howTo: 'Run Publish and grant › Publish the three assets.',
      links: [LINKS.apimMcp],
    },
    {
      id: 'key-minted',
      title: 'An access-contract api-key',
      detail: 'The published tool requires a subscription. Without a key the gateway returns 401 before the MCP runtime is reached.',
      howTo: 'Run Publish and grant › Deploy the mixed access contract, then paste the key into the Gateway access profile.',
      links: [LINKS.apimSubscriptions],
    },
    ...extra,
  ];
}

const MCP_DEVIATIONS = [
  'The notebook treats an HTTP 2xx `tools/list` response as success without checking for a JSON-RPC `error` member. This recipe fails on an error member regardless of status.',
  'The notebook prints the tool names it received but does not assert against an expected set. This recipe asserts that at least one tool is returned, and names the tools it expects without turning a remote server`s inventory into a hard requirement.',
];

const MCP_NOTES = [
  'The `Accept` header lists both `application/json` and `text/event-stream`, so APIM may answer either way. Both are parsed.',
  'The JSON-RPC id is numeric. APIM`s MCP runtime rejects a string id such as a UUID with "Invalid JSON payload".',
  'A browser cannot make this call against a different origin unless the gateway sends CORS headers permitting it and exposes the `Mcp-Session-Id` response header. That is why live execution is gated behind an executor rather than attempted with `fetch`.',
];

export const EXERCISE_SAMPLES = [
  {
    id: 'weather-mcp-discovery',
    group: 'exercise',
    title: 'Weather tool: MCP handshake and tools/list',
    shortTitle: 'Weather MCP discovery',
    summary: 'Open an MCP session against the API→MCP Weather Tool and list the tools it exposes.',
    purpose:
      'This is the first proof that an `mcp-from-api` asset actually works end to end: the gateway accepted the key, the MCP runtime answered the handshake, and the source API`s operations were projected into MCP tools.',
    explanation: [
      'An `mcp-from-api` server is generated by APIM from an existing API. Its endpoint carries a trailing `/mcp` on top of the asset-type prefix, so the full address is `{gateway}/mcp/{path}/mcp` — one `mcp` from the prefix and one from the runtime. That double segment is the single most common reason a handshake 404s.',
      'The handshake is two calls, not one. `initialize` negotiates the protocol version and returns an `Mcp-Session-Id` header; `tools/list` is only meaningful when that header is echoed back. Dropping the session header usually produces a 400 rather than an empty list, which is a useful signal.',
      'The tool inventory comes from the `operationNames` the publish contract exposed. With only `get-weather` published, exactly one tool should appear. More tools than expected means the contract exposed more operations than intended.',
    ],
    flow: [
      'POST `initialize` with protocol version `2025-06-18`, a numeric JSON-RPC id, and the contract key.',
      'Capture the `Mcp-Session-Id` response header.',
      'POST `tools/list` on that session with the next numeric id.',
      'Confirm the response carries a JSON-RPC `result` and at least one tool.',
    ],
    prerequisites: mcpDiscoveryPrerequisites([
      {
        id: 'source-api-in-product',
        title: '`weather-api` is in the same product',
        detail:
          'Not needed for `tools/list`, but a `tools/call` fails later without it because the forwarded key would not authorise the internal hop.',
        howTo: 'The access contract adds forwarded source APIs to the product automatically.',
        links: [LINKS.apimProduct],
      },
    ]),
    usesProfiles: ['hub', 'gatewayAccess'],
    fields: endpointFieldsFor({
      pathDefault: 'weather-tool-mcp',
      assetType: 'mcp-from-api',
      label: 'Weather tool',
      docLink: LINKS.apimMcp,
    }),
    risk: {
      level: 'read-only',
      effect:
        'Opens an MCP session and lists tools. No resource is created or changed, though the calls count against the contract`s tool rate limit and appear in usage telemetry.',
      blastRadius: 'Two requests.',
      reversibility: 'Not applicable.',
    },
    sourceCells: [19, 20],
    sourceNote: 'Cell 20 defines `mcp_call` / `validate_mcp` and runs the handshake for every tool asset.',
    expectedResults: [
      {
        id: 'initialize-ok',
        title: 'The handshake succeeds',
        assertion: 'HTTP 2xx with a JSON-RPC `result` and no `error`, and an `Mcp-Session-Id` response header.',
        evidence: 'The initialize response status, headers and body.',
        whenNotRun: 'Not run — the tool`s reachability is unknown.',
      },
      {
        id: 'tools-listed',
        title: 'At least one tool is returned',
        assertion: '`result.tools` is a non-empty array of objects each carrying a `name`.',
        evidence: 'The tools/list result.',
        whenNotRun: 'Not run.',
      },
      {
        id: 'expected-tool',
        title: 'The published operation appears as a tool',
        assertion: 'The tool list contains `get-weather`, matching the single operation the publish contract exposed.',
        evidence: 'The tool names.',
        whenNotRun: 'Not run.',
      },
    ],
    deviations: MCP_DEVIATIONS,
    notes: MCP_NOTES,
    build(ctx) {
      const endpoint = mcpEndpoint(
        { assetType: 'mcp-from-api', path: ctx.self('assetPath') },
        {
          gatewayUrl: ctx.get('hub.gatewayUrl'),
          useAssetTypePathPrefix: ctx.get('gatewayAccess.useAssetTypePathPrefix'),
          deployedEndpoint: ctx.self('deployedEndpoint'),
        },
      );
      const apiKeyHeader = ctx.get('gatewayAccess.subscriptionKeyHeader');
      return createExecutionPlan({
        sampleId: 'weather-mcp-discovery',
        title: 'Weather tool: MCP handshake and tools/list',
        summary: 'Initialize an MCP session against the API→MCP Weather Tool and list its tools.',
        risk: ctx.risk,
        sourceCells: [19, 20],
        steps: [
          mcpInitializeStep({ endpoint, apiKeyHeader, jsonRpcId: 1 }),
          mcpCallStep({
            id: 'tools-list',
            endpoint,
            apiKeyHeader,
            method: 'tools/list',
            params: {},
            jsonRpcId: 2,
            title: 'MCP tools/list',
            produces: ['status', 'result', 'toolNames'],
          }),
          step.assertion({
            id: 'assert-tools',
            title: 'Confirm the handshake and the tool inventory',
            detail: 'The session header binding is what makes the second call valid.',
            assertion: {
              kind: 'mcp-tools',
              source: '{{steps.tools-list.toolNames}}',
              expectations: [
                ...mcpHandshakeExpectations('Weather Tool'),
                '`tools/list` returns a non-empty `result.tools` array.',
                'The list contains `get-weather`.',
              ],
              endpoint,
            },
            produces: ['discovered'],
          }),
        ],
        expectedResults: ctx.expectedResults,
        notes: ctx.notes,
        deviations: ctx.deviations,
      });
    },
  },

  {
    id: 'learn-mcp-discovery',
    group: 'exercise',
    title: 'Microsoft Learn tool: MCP handshake and tools/list',
    shortTitle: 'Learn MCP discovery',
    summary: 'Open an MCP session against the gateway-fronted Microsoft Learn MCP server and list its tools.',
    purpose:
      'Proves the second publishing shape works: an `mcp-existing` asset, where the gateway fronts a remote MCP server it did not generate. Success here also proves the backend and its circuit breaker were created, because the request has to traverse them.',
    explanation: [
      'A native MCP server keeps its own address space. The gateway adds the asset-type prefix but no trailing `/mcp`, so the endpoint is `{gateway}/mcp/{path}` — one segment shorter than the API→MCP form. Getting this wrong in either direction produces a 404 that looks like a publishing failure.',
      'The remote backend is Microsoft Learn`s public MCP endpoint, published with `authType: none` because it is unauthenticated. The gateway still requires the contract key, so the asset is protected even though its backend is not.',
      'The tool inventory belongs to the remote server, not to this contract. Asserting an exact list would make this recipe fail whenever Microsoft ships a new tool, so the hard assertion is "at least one tool", with the currently published documentation-search tools named as an informational expectation.',
    ],
    flow: [
      'POST `initialize` with protocol version `2025-06-18` and the contract key.',
      'Capture the `Mcp-Session-Id` response header.',
      'POST `tools/list` on that session.',
      'Confirm a JSON-RPC `result` with a non-empty tool array.',
    ],
    prerequisites: mcpDiscoveryPrerequisites([
      {
        id: 'egress',
        title: 'Outbound access from the gateway to learn.microsoft.com',
        detail: 'The gateway calls the remote MCP server itself. A network-restricted APIM instance needs egress to `learn.microsoft.com`.',
        howTo: 'Check the gateway`s outbound rules or NSG, and the backend`s health in the APIM portal.',
        links: [LINKS.learnMcpServer],
      },
    ]),
    usesProfiles: ['hub', 'gatewayAccess'],
    fields: endpointFieldsFor({
      pathDefault: 'ms-learn-tool-mcp',
      assetType: 'mcp-existing',
      label: 'Learn tool',
      docLink: LINKS.learnMcpServer,
    }),
    risk: {
      level: 'read-only',
      effect: 'Opens an MCP session against a remote server through the gateway. Nothing is created or changed.',
      blastRadius: 'Two requests, one of which reaches a public Microsoft endpoint.',
      reversibility: 'Not applicable.',
    },
    sourceCells: [19, 20],
    sourceNote: 'Cell 20 runs the same `validate_mcp` handshake for every asset whose type is `mcp-from-api` or `mcp-existing`.',
    expectedResults: [
      {
        id: 'initialize-ok',
        title: 'The handshake succeeds through the gateway',
        assertion: 'HTTP 2xx with a JSON-RPC `result` and an `Mcp-Session-Id` header.',
        evidence: 'The initialize response.',
        whenNotRun: 'Not run — the remote tool`s reachability is unknown.',
      },
      {
        id: 'tools-listed',
        title: 'At least one tool is returned',
        assertion: '`result.tools` is a non-empty array.',
        evidence: 'The tools/list result.',
        whenNotRun: 'Not run.',
      },
      {
        id: 'backend-traversed',
        title: 'The published backend was traversed',
        assertion:
          'A successful response implies the `ms-learn-tool-backend` backend exists and is reachable, which is the object the resiliency recipe inspects.',
        evidence: 'The successful round trip.',
        whenNotRun: 'Not run.',
      },
    ],
    deviations: [
      ...MCP_DEVIATIONS,
      'The notebook prints whatever tool names come back. Because these belong to a remote Microsoft service and change over time, this recipe does not treat any specific name as required.',
    ],
    notes: [
      ...MCP_NOTES,
      'At the time of writing the Microsoft Learn MCP server publishes documentation search and fetch tools. Treat the exact names as informational.',
    ],
    build(ctx) {
      const endpoint = mcpEndpoint(
        { assetType: 'mcp-existing', path: ctx.self('assetPath') },
        {
          gatewayUrl: ctx.get('hub.gatewayUrl'),
          useAssetTypePathPrefix: ctx.get('gatewayAccess.useAssetTypePathPrefix'),
          deployedEndpoint: ctx.self('deployedEndpoint'),
        },
      );
      const apiKeyHeader = ctx.get('gatewayAccess.subscriptionKeyHeader');
      return createExecutionPlan({
        sampleId: 'learn-mcp-discovery',
        title: 'Microsoft Learn tool: MCP handshake and tools/list',
        summary: 'Initialize an MCP session against the gateway-fronted remote MCP server and list its tools.',
        risk: ctx.risk,
        sourceCells: [19, 20],
        steps: [
          mcpInitializeStep({ endpoint, apiKeyHeader, jsonRpcId: 1 }),
          mcpCallStep({
            id: 'tools-list',
            endpoint,
            apiKeyHeader,
            method: 'tools/list',
            params: {},
            jsonRpcId: 2,
            title: 'MCP tools/list',
            produces: ['status', 'result', 'toolNames'],
          }),
          step.assertion({
            id: 'assert-tools',
            title: 'Confirm the handshake and a non-empty inventory',
            detail: 'The remote server owns the inventory, so only its non-emptiness is required.',
            assertion: {
              kind: 'mcp-tools',
              source: '{{steps.tools-list.toolNames}}',
              expectations: [
                ...mcpHandshakeExpectations('Microsoft Learn Tool'),
                '`tools/list` returns a non-empty `result.tools` array.',
                'The exact tool names are informational: they belong to the remote Microsoft Learn MCP server.',
              ],
              endpoint,
            },
            produces: ['discovered'],
          }),
        ],
        expectedResults: ctx.expectedResults,
        notes: ctx.notes,
        deviations: ctx.deviations,
      });
    },
  },

  {
    id: 'a2a-agent-card',
    group: 'exercise',
    title: 'A2A agent card',
    shortTitle: 'A2A card',
    summary: 'Fetch the agent card the gateway re-exposes at `/.well-known/agent.json`.',
    purpose:
      'An A2A client discovers an agent by reading its card. The publish contract rewrites the card`s transport URLs to the gateway, so this recipe proves both that the card is reachable and that a client following it will route through the gateway rather than calling Foundry directly.',
    explanation: [
      'The card lives at a well-known path relative to the agent base — `{gateway}/agent/{path}/.well-known/agent.json` with the asset-type prefix on. The gateway fetches it from the Foundry agent card backend and rewrites it before returning it.',
      'The rewrite is the point. If the card still advertised `…services.ai.azure.com…` transport URLs, an A2A client would resolve the card through the gateway and then send its actual messages straight to Foundry, bypassing the product policy, the rate limits and the usage telemetry entirely. Checking the transport URLs is therefore a security check, not a cosmetic one.',
      'The card endpoint is subscription-protected like the rest of the asset, so the contract key must be presented on the card fetch as well as on the JSON-RPC calls.',
    ],
    flow: [
      'GET `{agent base}/.well-known/agent.json` with the contract key in the configured header.',
      'Confirm HTTP 2xx and a JSON body.',
      'Confirm the card carries a name and a description.',
      'Confirm every transport URL in the card points at the gateway host, not at Foundry.',
    ],
    prerequisites: [
      {
        id: 'a2a-published',
        title: 'The A2A asset is published',
        detail: 'The card path only exists once the publish contract created the agent API.',
        howTo: 'Run Publish and grant › Publish the three assets with the A2A asset enabled.',
        links: [LINKS.foundryA2a],
      },
      {
        id: 'key-minted',
        title: 'An access-contract api-key',
        detail: 'The A2A API is published with `subscriptionRequired: true`.',
        howTo: 'Run Publish and grant › Deploy the mixed access contract.',
        links: [LINKS.apimSubscriptions],
      },
    ],
    usesProfiles: ['hub', 'gatewayAccess', 'foundry'],
    fields: [
      {
        name: 'agentPath',
        label: 'Agent path',
        type: 'string',
        classification: 'sample-default',
        width: 'short',
        default: 'hr-chat-agent',
        help: 'Used when no deployed path is recorded. With the asset-type prefix on, the agent base is `{gateway}/agent/{path}`.',
        howToObtain: 'Fixed by the notebook (cell 14).',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 14 asset 3 `path`',
      },
      {
        name: 'deployedPath',
        label: 'Deployed path (authoritative)',
        type: 'string',
        classification: 'derived',
        width: 'id',
        default: '',
        derivedFrom: 'Produced by Publish and grant › Publish the three assets (`publishedAssets[].path`).',
        help: 'The already-prefixed path the deployment reported. When set it wins over the composed path.',
        howToObtain: 'Copy it from the publish deployment`s `publishedAssets` output.',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 20 `agent_endpoint`',
      },
      {
        name: 'agentCardPath',
        label: 'Agent card path',
        type: 'string',
        classification: 'sample-default',
        width: 'short',
        default: '/.well-known/agent.json',
        help: 'Relative card path. A2A clients resolve it against the agent base URL.',
        howToObtain: 'Fixed by the notebook (cell 22).',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 22 `card_url`',
      },
    ],
    risk: {
      level: 'read-only',
      effect: 'One GET. Nothing is created or changed, though it counts against the agent rate limit.',
      blastRadius: 'One request.',
      reversibility: 'Not applicable.',
    },
    sourceCells: [21, 22],
    sourceNote: 'Cell 22 fetches the card with the api-key and records `results["hr-chat-agent-card"]` from the status code alone.',
    expectedResults: [
      {
        id: 'card-reachable',
        title: 'The card is reachable',
        assertion: 'HTTP 2xx and a body that parses as JSON.',
        evidence: 'The response status and body.',
        whenNotRun: 'Not run — the card`s reachability is unknown.',
      },
      {
        id: 'card-shape',
        title: 'The card describes the agent',
        assertion: 'The card carries a `name` and a `description`, which is what an A2A client shows and what `A2AAgent` requires.',
        evidence: 'The parsed card.',
        whenNotRun: 'Not run.',
      },
      {
        id: 'transport-rewritten',
        title: 'Transport URLs point at the gateway',
        assertion:
          'Every transport URL in the card resolves to the gateway host. A URL still pointing at `*.services.ai.azure.com` means a client would bypass the gateway.',
        evidence: 'The card`s `url` and any additional interface URLs.',
        whenNotRun: 'Not run — bypass risk is unverified.',
      },
    ],
    deviations: [
      'The notebook records success from the status code alone and never inspects the card body. This recipe additionally checks the card shape and, importantly, that the transport URLs were rewritten to the gateway.',
    ],
    notes: [
      'A browser can only make this call cross-origin when the gateway returns permissive CORS headers. The card path is a plain GET, so it is the most likely of these recipes to work from a browser, but it is still not assumed.',
    ],
    build(ctx) {
      const base = agentEndpoint(
        { assetType: 'a2a', path: ctx.self('agentPath') },
        {
          gatewayUrl: ctx.get('hub.gatewayUrl'),
          useAssetTypePathPrefix: ctx.get('gatewayAccess.useAssetTypePathPrefix'),
          deployedPath: ctx.self('deployedPath'),
        },
      );
      const cardUrl = agentCardUrl(base, ctx.self('agentCardPath'));
      const apiKeyHeader = ctx.get('gatewayAccess.subscriptionKeyHeader');
      return createExecutionPlan({
        sampleId: 'a2a-agent-card',
        title: 'A2A agent card',
        summary: 'Fetch and inspect the agent card the gateway re-exposes.',
        risk: ctx.risk,
        sourceCells: [21, 22],
        steps: [
          step.http({
            id: 'get-card',
            title: 'GET the agent card',
            detail: 'The card path is subscription-protected like the rest of the asset.',
            request: {
              method: 'GET',
              url: cardUrl,
              headers: {
                [apiKeyHeader]: secretRef('gatewayAccess.apiKey', { label: 'Access-contract api-key' }),
                Accept: 'application/json',
              },
              capture: { status: 'response.status', card: 'response.json' },
              timeoutSeconds: 60,
            },
            produces: ['status', 'card'],
          }),
          step.assertion({
            id: 'assert-card',
            title: 'Confirm the card and its transport URLs',
            detail: 'A card still advertising Foundry transport URLs would let clients bypass the gateway.',
            assertion: {
              kind: 'a2a-card',
              source: '{{steps.get-card.card}}',
              expectations: [
                'HTTP status is 2xx.',
                'The body parses as JSON.',
                'The card carries `name` and `description`.',
                `Every transport URL in the card starts with ${ctx.get('hub.gatewayUrl') || 'the gateway URL'}.`,
                'No transport URL points at `*.services.ai.azure.com`.',
              ],
              endpoint: cardUrl,
            },
            produces: ['cardOk'],
          }),
        ],
        expectedResults: ctx.expectedResults,
        notes: ctx.notes,
        deviations: ctx.deviations,
      });
    },
  },

  {
    id: 'a2a-message-send',
    group: 'exercise',
    title: 'A2A message/send through the gateway',
    shortTitle: 'A2A message',
    summary: 'Send a JSON-RPC `message/send` that the gateway proxies to Foundry with its managed identity.',
    purpose:
      'This is the full A2A path: consumer key at the gateway, managed identity from the gateway to Foundry, and an agent response back. It is also the recipe where the notebook`s success criterion is weakest, because a JSON-RPC error arrives inside an HTTP 200.',
    explanation: [
      'The request is a JSON-RPC 2.0 call to the agent base URL with `jsonRpcPath: "/"`, so there is no extra path segment. The `params.message` object must carry `kind: "message"` — Foundry serves A2A v0.3 by default and rejects a message object without it.',
      'The JSON-RPC id must be numeric here for the same reason it must be numeric for MCP. The notebook hard-codes `1`; the `messageId` inside the message is a client-generated correlation id and the notebook uses a random UUID, which makes its request non-reproducible. This recipe exposes it as an input with a fixed default so the generated plan is stable.',
      'A JSON-RPC error is returned with HTTP 200. The notebook checks `rr.status_code < 300` and records a pass, so a response body of `{"jsonrpc":"2.0","id":1,"error":{"code":-32603,...}}` is counted as success. This recipe fails on any `error` member regardless of status, and reports the code and message.',
      'Header handling across the notebook is inconsistent: this cell sends only `Content-Type` and the api-key, while the burst cell also sends `A2A-Version: 1.0`. The version header is exposed here as an optional input, defaulting to the notebook`s behaviour for this cell.',
    ],
    flow: [
      'POST a JSON-RPC `message/send` to the agent base URL with the contract key.',
      'Confirm HTTP 2xx.',
      'Confirm the JSON-RPC body has a `result` and no `error`.',
      'Read the returned message or task from the result.',
    ],
    prerequisites: [
      {
        id: 'identity-granted',
        title: 'The APIM identity has the Foundry role',
        detail: 'The gateway authenticates to Foundry with its managed identity. Without the grant this call fails at the backend with 401 or 403.',
        howTo: 'Run Prepare › Grant the APIM identity Foundry access.',
        links: [LINKS.foundryRbac],
      },
      {
        id: 'a2a-enabled',
        title: 'A2A is enabled on the agent',
        detail: 'Foundry rejects A2A traffic for an agent whose `a2a` protocol configuration was never activated.',
        howTo: 'Run Prepare › Enable incoming A2A on the Foundry agent.',
        links: [LINKS.foundryA2a],
      },
      {
        id: 'key-minted',
        title: 'An access-contract api-key',
        detail:
          'The A2A API is published with `subscriptionRequired: true`, so the gateway rejects the call with 401 before it ever reaches Foundry if no key is presented.',
        howTo: 'Run Publish and grant › Deploy the mixed access contract.',
        links: [LINKS.apimSubscriptions],
      },
    ],
    usesProfiles: ['hub', 'gatewayAccess', 'foundry'],
    fields: [
      {
        name: 'agentPath',
        label: 'Agent path',
        type: 'string',
        classification: 'sample-default',
        width: 'short',
        default: 'hr-chat-agent',
        help: 'Used when no deployed path is recorded.',
        howToObtain: 'Fixed by the notebook (cell 14).',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 14 asset 3 `path`',
      },
      {
        name: 'deployedPath',
        label: 'Deployed path (authoritative)',
        type: 'string',
        classification: 'derived',
        width: 'id',
        default: '',
        derivedFrom: 'Produced by Publish and grant › Publish the three assets.',
        help: 'The already-prefixed path the deployment reported.',
        howToObtain: 'Copy it from `publishedAssets[].path`.',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 20 `agent_endpoint`',
      },
      {
        name: 'question',
        label: 'Message text',
        type: 'multiline',
        classification: 'sample-default',
        width: 'long',
        default: 'What can you help me with?',
        help: 'The single text part sent in the message.',
        howToObtain: 'Fixed by the notebook (cell 22).',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 22 message text',
      },
      {
        name: 'messageId',
        label: 'Message id',
        type: 'string',
        classification: 'sample-default',
        width: 'id',
        default: 'citadel-playground-message-01',
        help: 'Client-generated correlation id. The notebook uses a random UUID, which makes its request different on every run; a fixed value keeps the generated plan reproducible.',
        howToObtain: 'Any stable string. Use a UUID if you need per-request correlation in your own telemetry.',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 22 `str(uuid.uuid4())`',
      },
      {
        name: 'a2aVersionHeader',
        label: 'A2A-Version header',
        type: 'string',
        classification: 'sample-default',
        width: 'num',
        default: '',
        help: 'Left empty to match this notebook cell. The burst cell sends `1.0` for the same endpoint — that inconsistency is a known risk, not a rule.',
        howToObtain: 'Set `1.0` to match cell 31, or leave empty to match cell 22.',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 22 omits it; cell 31 sends `A2A-Version: 1.0`',
      },
    ],
    risk: {
      level: 'read-only',
      effect:
        'Sends one message to a live agent. No Azure resource changes, but the agent runs an inference and the call is billed and logged.',
      blastRadius: 'One agent invocation.',
      reversibility: 'Not applicable. The agent may retain the interaction in its own thread history.',
    },
    sourceCells: [21, 22],
    sourceNote: 'Cell 22 posts `message/send` and records `results["hr-chat-agent-rpc"]` from the status code alone.',
    expectedResults: [
      {
        id: 'http-ok',
        title: 'HTTP 2xx',
        assertion: 'The gateway accepted the call and reached the backend.',
        evidence: 'The response status.',
        whenNotRun: 'Not run.',
      },
      {
        id: 'no-jsonrpc-error',
        title: 'No JSON-RPC error member',
        assertion:
          'The body has a `result` and no `error`. An HTTP 200 carrying `error` is a failure here, and reports the JSON-RPC code and message.',
        evidence: 'The parsed JSON-RPC body.',
        whenNotRun: 'Not run.',
      },
      {
        id: 'agent-response',
        title: 'The agent produced a response',
        assertion: 'The result carries a message or task, and any message part with `kind: "text"` holds non-empty text.',
        evidence: 'The JSON-RPC result.',
        whenNotRun: 'Not run.',
      },
    ],
    deviations: [
      'The notebook records this call as a pass whenever the HTTP status is below 300. A JSON-RPC error inside an HTTP 200 is therefore counted as success. This recipe treats it as a failure.',
      'The notebook reports a non-2xx as a warning rather than an error, so the summary can read as passing while the call did not work.',
      'The notebook generates the `messageId` with `uuid.uuid4()`. This recipe uses a fixed default so the plan is reproducible, and says so.',
    ],
    notes: [
      'Foundry serves A2A v0.3 by default, which requires `kind: "message"` inside `params.message`. Omitting it produces a JSON-RPC validation error rather than an HTTP error.',
      'The gateway, not the caller, authenticates to Foundry. A 401 or 403 in the JSON-RPC error is about the APIM identity`s role, not about the api-key.',
    ],
    build(ctx) {
      const base = agentEndpoint(
        { assetType: 'a2a', path: ctx.self('agentPath') },
        {
          gatewayUrl: ctx.get('hub.gatewayUrl'),
          useAssetTypePathPrefix: ctx.get('gatewayAccess.useAssetTypePathPrefix'),
          deployedPath: ctx.self('deployedPath'),
        },
      );
      const apiKeyHeader = ctx.get('gatewayAccess.subscriptionKeyHeader');
      const versionHeader = ctx.self('a2aVersionHeader');
      const headers = {
        'Content-Type': 'application/json',
        [apiKeyHeader]: secretRef('gatewayAccess.apiKey', { label: 'Access-contract api-key' }),
      };
      if (versionHeader) headers['A2A-Version'] = versionHeader;
      return createExecutionPlan({
        sampleId: 'a2a-message-send',
        title: 'A2A message/send through the gateway',
        summary: 'Send one JSON-RPC message to the published agent and judge the JSON-RPC body, not just the status.',
        risk: ctx.risk,
        sourceCells: [21, 22],
        steps: [
          step.http({
            id: 'message-send',
            title: 'POST message/send',
            detail: '`jsonRpcPath` is `/`, so the agent base URL is the JSON-RPC endpoint.',
            request: {
              method: 'POST',
              url: base,
              headers,
              body: {
                jsonrpc: '2.0',
                id: 1,
                method: 'message/send',
                params: {
                  message: {
                    kind: 'message',
                    role: 'user',
                    messageId: ctx.self('messageId'),
                    parts: [{ kind: 'text', text: ctx.self('question') }],
                  },
                },
              },
              capture: {
                status: 'response.status',
                result: 'response.jsonrpc.result',
                error: 'response.jsonrpc.error',
              },
              timeoutSeconds: 120,
            },
            produces: ['status', 'result', 'error'],
          }),
          step.assertion({
            id: 'assert-jsonrpc',
            title: 'Require a JSON-RPC result, not just a 2xx',
            detail: 'An HTTP 2xx with an `error` member is a failure.',
            assertion: {
              kind: 'jsonrpc',
              source: '{{steps.message-send.error}}',
              expectations: [
                'HTTP status is 2xx.',
                'The body has no `error` member. An HTTP 2xx carrying `error` fails, and the code and message are reported.',
                'The body has a `result`.',
                'Any text part in the result holds non-empty text.',
              ],
              endpoint: base,
            },
            produces: ['answered'],
          }),
        ],
        expectedResults: ctx.expectedResults,
        notes: ctx.notes,
        deviations: ctx.deviations,
      });
    },
  },

  {
    id: 'agent-framework-hr-question',
    group: 'exercise',
    title: 'Agent Framework: ask the HR agent',
    shortTitle: 'Agent Framework question',
    summary: 'Resolve the published card with a real A2A client and ask an HR question through the gateway.',
    purpose:
      'The previous recipes prove the protocol works. This one proves the asset is usable by an off-the-shelf client: Microsoft Agent Framework`s `A2AAgent` resolves the card, follows its transport URLs, and gets an answer — all through the gateway, presenting the contract key on every call.',
    explanation: [
      'The client is given the gateway`s agent base URL and an HTTP client pre-loaded with the api-key header. `A2ACardResolver` fetches `/.well-known/agent.json`, and `A2AAgent` then follows the transport URLs inside that card. Because the publish contract rewrote them to the gateway, every subsequent call also carries the key and is subject to the product policy.',
      'That is exactly why the card-rewrite assertion in the agent-card recipe matters. If the card advertised Foundry directly, this client would resolve through the gateway and then talk to Foundry without a key — and it would still appear to work.',
      'This is a Python step. It needs `agent-framework` and `agent-framework-a2a` at matching versions, plus `httpx`, the `a2a` client package and `nest_asyncio` to run an event loop inside a notebook. There is no browser equivalent, so the default executor reports this recipe as blocked rather than attempting it.',
    ],
    flow: [
      'Create an HTTP client whose default headers include the contract key.',
      'Resolve the agent card at `/.well-known/agent.json` relative to the gateway agent base.',
      'Construct an `A2AAgent` from the resolved card.',
      'Run the question and join the text of the returned messages.',
      'Confirm the joined answer is non-empty.',
    ],
    prerequisites: [
      {
        id: 'python-packages',
        title: 'Agent Framework packages installed and version-aligned',
        detail: '`agent-framework` and `agent-framework-a2a` must be installed together and kept at matching versions.',
        howTo: 'Run `pip install -U agent-framework agent-framework-a2a`, which also pulls the `a2a` client package.',
        links: [LINKS.agentFramework],
      },
      {
        id: 'card-rewritten',
        title: 'The card`s transport URLs point at the gateway',
        detail: 'If they do not, this client silently bypasses the gateway and the result proves nothing about the contract.',
        howTo: 'Run Exercise › A2A agent card first and check the transport-URL assertion.',
        links: [LINKS.foundryA2a],
      },
      {
        id: 'agent-answers',
        title: 'The agent can answer the question',
        detail:
          'The prompt agent must have instructions or grounding that let it respond. An empty answer fails this recipe even though the transport worked.',
        howTo: 'Ask the same question in the Foundry portal playground first.',
        links: [LINKS.foundryA2a],
      },
    ],
    usesProfiles: ['hub', 'gatewayAccess', 'foundry'],
    fields: [
      {
        name: 'agentPath',
        label: 'Agent path',
        type: 'string',
        classification: 'sample-default',
        width: 'short',
        default: 'hr-chat-agent',
        help: 'Used when no deployed path is recorded.',
        howToObtain: 'Fixed by the notebook (cell 14).',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 14 asset 3 `path`',
      },
      {
        name: 'deployedPath',
        label: 'Deployed path (authoritative)',
        type: 'string',
        classification: 'derived',
        width: 'id',
        default: '',
        derivedFrom: 'Produced by Publish and grant › Publish the three assets.',
        help: 'The already-prefixed path the deployment reported.',
        howToObtain: 'Copy it from `publishedAssets[].path`.',
        links: [LINKS.foundryA2a],
        notebookRef: 'cell 28 `agent_endpoint`',
      },
      {
        name: 'question',
        label: 'Question',
        type: 'multiline',
        classification: 'sample-default',
        width: 'long',
        default: 'What is our leave policy?',
        help: 'The question put to the HR agent.',
        howToObtain: 'Fixed by the notebook (cell 28).',
        links: [LINKS.agentFramework],
        notebookRef: 'cell 28 `ask_hr_agent("What is our leave policy?")`',
      },
      {
        name: 'timeoutSeconds',
        label: 'Client timeout (seconds)',
        type: 'integer',
        classification: 'sample-default',
        width: 'num',
        default: 120,
        min: 5,
        max: 600,
        help: 'HTTP client timeout. An agent turn can take tens of seconds.',
        howToObtain: 'Fixed by the notebook (cell 28 `httpx.AsyncClient(timeout=120.0)`).',
        links: [LINKS.agentFramework],
        notebookRef: 'cell 28 timeout',
      },
    ],
    risk: {
      level: 'read-only',
      effect: 'Runs one agent turn. No Azure resource changes; the inference is billed and logged.',
      blastRadius: 'One agent invocation plus one card fetch.',
      reversibility: 'Not applicable.',
    },
    sourceCells: [27, 28],
    sourceNote:
      'Cell 28 uses `A2ACardResolver` and `A2AAgent` with an api-key-bearing httpx client, and records `results["hr-chat-agent-maf"]` from whether the answer is non-empty.',
    expectedResults: [
      {
        id: 'card-resolved',
        title: 'The card resolves through the gateway',
        assertion: '`A2ACardResolver.get_agent_card` succeeds against the gateway base with the api-key header set.',
        evidence: 'The resolved card object.',
        whenNotRun: 'Not run — no Python runtime is attached.',
      },
      {
        id: 'answer-returned',
        title: 'The agent answers',
        assertion: 'The joined text of the returned messages is non-empty after trimming.',
        evidence: 'The response messages.',
        whenNotRun: 'Not run.',
      },
      {
        id: 'through-gateway',
        title: 'Traffic went through the gateway',
        assertion:
          'The transport URLs the client followed are gateway URLs, so the call was subject to the product policy and appears in `a2a-usage` telemetry.',
        evidence: 'The card`s transport URLs, plus a matching increase in the A2A usage metric.',
        whenNotRun: 'Not run.',
      },
    ],
    deviations: [
      'The notebook catches every exception, prints an install hint and records a failure. This recipe reports the exception type and message rather than collapsing all causes into one.',
      'The notebook does not verify that the client actually traversed the gateway. This recipe states it as an expected result to be corroborated with the usage metric, and does not claim it from a successful answer alone.',
    ],
    notes: [
      'This is a `library` step. The shipped executor cannot run Python, so this recipe reports `blocked` until an adapter that supports `library` steps is attached.',
      '`nest_asyncio` is only needed because the notebook calls `asyncio.run` inside an already-running loop. Outside a notebook it can be dropped.',
    ],
    build(ctx) {
      const base = agentEndpoint(
        { assetType: 'a2a', path: ctx.self('agentPath') },
        {
          gatewayUrl: ctx.get('hub.gatewayUrl'),
          useAssetTypePathPrefix: ctx.get('gatewayAccess.useAssetTypePathPrefix'),
          deployedPath: ctx.self('deployedPath'),
        },
      );
      const apiKeyHeader = ctx.get('gatewayAccess.subscriptionKeyHeader');
      const timeout = ctx.self('timeoutSeconds');
      const code = [
        'import asyncio, os',
        'import httpx, nest_asyncio',
        'from a2a.client import A2ACardResolver',
        'from agent_framework.a2a import A2AAgent',
        'nest_asyncio.apply()',
        '',
        `agent_url = ${JSON.stringify(base)}`,
        '# The key is read from the environment; it is never written into this snippet.',
        'api_key = os.environ["CITADEL_GATEWAY_ACCESS_API_KEY"]',
        '',
        'async def ask_hr_agent(question):',
        `    async with httpx.AsyncClient(timeout=${timeout}.0, headers={${JSON.stringify(apiKeyHeader)}: api_key}) as http_client:`,
        '        resolver = A2ACardResolver(httpx_client=http_client, base_url=agent_url)',
        `        card = await resolver.get_agent_card(relative_card_path=${JSON.stringify('/.well-known/agent.json')})`,
        '        agent = A2AAgent(name=card.name, description=card.description, agent_card=card, http_client=http_client)',
        '        resp = await agent.run(question)',
        '        return "\\n".join(getattr(m, "text", "") for m in resp.messages)',
        '',
        `answer = asyncio.run(ask_hr_agent(${JSON.stringify(ctx.self('question'))}))`,
        'print(answer)',
      ].join('\n');
      return createExecutionPlan({
        sampleId: 'agent-framework-hr-question',
        title: 'Agent Framework: ask the HR agent',
        summary: 'Resolve the published card with `A2ACardResolver` and answer a question with `A2AAgent`.',
        risk: ctx.risk,
        sourceCells: [27, 28],
        steps: [
          step.library({
            id: 'ask-agent',
            title: 'Resolve the card and run the question',
            detail: 'The api-key is supplied through the environment, so it never appears in the snippet or the preview.',
            library: {
              runtime: 'python>=3.10',
              packages: ['agent-framework', 'agent-framework-a2a', 'httpx', 'nest_asyncio'],
              install: 'pip install -U agent-framework agent-framework-a2a httpx nest_asyncio',
              entry: 'A2ACardResolver.get_agent_card + A2AAgent.run',
              secretEnv: { CITADEL_GATEWAY_ACCESS_API_KEY: secretRef('gatewayAccess.apiKey') },
              code,
            },
            produces: ['answer', 'card'],
          }),
          step.assertion({
            id: 'assert-answer',
            title: 'Confirm a non-empty answer arrived through the gateway',
            detail: 'A non-empty answer proves the round trip; the usage metric proves it went through the gateway.',
            assertion: {
              kind: 'non-empty',
              source: '{{steps.ask-agent.answer}}',
              expectations: [
                'The card resolved from the gateway base URL.',
                'The joined answer text is non-empty after trimming.',
                'The card`s transport URLs are gateway URLs, so the run is attributable to the contract.',
                'Corroborate with the `a2a-usage` metric rather than assuming the route from a successful answer.',
              ],
              endpoint: base,
            },
            produces: ['answered'],
          }),
        ],
        expectedResults: ctx.expectedResults,
        notes: ctx.notes,
        deviations: ctx.deviations,
      });
    },
  },

  {
    id: 'weather-tools-call',
    group: 'exercise',
    title: 'Weather tool: direct tools/call',
    shortTitle: 'Weather tools/call',
    summary: 'Invoke `get-weather` through the gateway and check the payload the mock policy returns.',
    purpose:
      'A successful `tools/list` only proves the tool was projected. This recipe proves the whole chain works: the gateway authorises the caller, the MCP runtime forwards the call to the protected source API with the caller`s key injected into the custom header, and the source API`s mock policy answers.',
    explanation: [
      'Two calls again: `initialize` to open the session, then `tools/call` with the tool name and its arguments on that session. This is where the key-forwarding design is actually exercised — a failure here after a successful `tools/list` almost always means `weather-api` is not in the same product, so the forwarded key does not authorise the internal hop.',
      'The result arrives as MCP content blocks. The first block`s `text` holds the JSON document the mock policy produced, so it is parsed a second time to reach the fields.',
      'The mock policy has a branch worth asserting. Seattle, New York City and Los Angeles return `temperature_format: "Fahrenheit"`; every other city returns `"Celsius"`. Everything else in the payload is randomised — temperature, description, humidity and wind speed all change per call — so the assertions check field presence, types and the unit branch rather than values.',
    ],
    flow: [
      'POST `initialize` and capture the session id.',
      'POST `tools/call` with `{ name, arguments }` on that session.',
      'Read `result.content[0].text` and parse it as JSON.',
      'Confirm the six expected fields are present and that the temperature unit matches the city.',
    ],
    prerequisites: [
      {
        id: 'source-in-product',
        title: '`weather-api` is in the same product as the tool',
        detail:
          'The forwarded key must authorise the internal hop to the protected source API. Without it, `tools/list` succeeds and `tools/call` fails.',
        howTo: 'The access contract adds forwarded source APIs automatically. Confirm the product`s API list includes `weather-api`.',
        links: [LINKS.apimProduct],
      },
      {
        id: 'forwarding-on',
        title: 'Key forwarding is enabled on the tool',
        detail: '`forwardSubscriptionKeyToSource: true` and a `sourceSubscriptionKeyHeaderName` matching the source API.',
        howTo: 'Both are set by the publish contract. The header must be the same custom name on both sides.',
        links: [LINKS.apimMcp],
      },
    ],
    usesProfiles: ['hub', 'gatewayAccess'],
    fields: [
      ...endpointFieldsFor({
        pathDefault: 'weather-tool-mcp',
        assetType: 'mcp-from-api',
        label: 'Weather tool',
        docLink: LINKS.apimMcp,
      }),
      {
        name: 'toolName',
        label: 'Tool name',
        type: 'string',
        classification: 'sample-default',
        width: 'short',
        default: 'get-weather',
        help: 'The MCP tool name, which matches the source API operation the publish contract exposed.',
        howToObtain: 'Fixed by the notebook (cell 29). Confirm it appears in `tools/list`.',
        links: [LINKS.apimMcp],
        notebookRef: 'cell 29 `call_mcp_tool(weather_asset, "get-weather", ...)`',
      },
      {
        name: 'city',
        label: 'City',
        type: 'string',
        classification: 'sample-default',
        width: 'short',
        default: 'London',
        help: 'The single argument. Seattle, New York City and Los Angeles return Fahrenheit; everything else returns Celsius.',
        howToObtain: 'Fixed by the notebook (cell 29 uses `London`). Any city string is accepted by the mock policy.',
        links: [LINKS.apimMcp],
        notebookRef: 'cell 29 `{"city": "London"}`',
      },
    ],
    risk: {
      level: 'read-only',
      effect: 'Invokes a tool that returns synthetic data from a mock policy. No real backend is called and nothing is changed.',
      blastRadius: 'Two requests, counted against the tool rate limit.',
      reversibility: 'Not applicable.',
    },
    sourceCells: [29],
    sourceNote:
      'Cell 29 defines `call_mcp_tool`, invokes `get-weather` for London, prints the first content block and records `results["weather-tool-toolcall"]` from whether content was returned.',
    expectedResults: [
      {
        id: 'call-succeeds',
        title: 'The tool call returns content',
        assertion: 'HTTP 2xx, a JSON-RPC `result` with no `error`, and a non-empty `result.content` array.',
        evidence: 'The tools/call response.',
        whenNotRun: 'Not run — the forwarding path is unverified.',
      },
      {
        id: 'payload-fields',
        title: 'The payload carries the expected fields',
        assertion:
          '`result.content[0].text` parses as JSON holding `city`, `temperature`, `temperature_format`, `description`, `humidity` and `wind_speed`.',
        evidence: 'The parsed payload.',
        whenNotRun: 'Not run.',
      },
      {
        id: 'unit-branch',
        title: 'The temperature unit matches the city',
        assertion:
          'Seattle, New York City and Los Angeles return `Fahrenheit`; every other city returns `Celsius`. This is the branch in the accelerator`s mock policy.',
        evidence: 'The `temperature_format` field.',
        whenNotRun: 'Not run.',
      },
      {
        id: 'echoed-city',
        title: 'The city is echoed back',
        assertion: 'The `city` field equals the argument sent, confirming the argument reached the source API.',
        evidence: 'The `city` field.',
        whenNotRun: 'Not run.',
      },
    ],
    deviations: [
      'The notebook records success from `bool(content)` alone, so an error string returned as a content block would count as a pass. This recipe parses the payload and asserts the field set and the unit branch.',
      'The notebook falls back to `json.dumps(out)` when there is no content, printing whatever came back without changing the recorded result.',
    ],
    notes: [
      'Everything except `city` and `temperature_format` is randomised by the mock policy, so value assertions would be flaky by construction. Presence, type and the unit branch are the stable properties.',
      'A `tools/call` that fails with 401 after a successful `tools/list` points at product membership for `weather-api`, not at the MCP server.',
    ],
    build(ctx) {
      const endpoint = mcpEndpoint(
        { assetType: 'mcp-from-api', path: ctx.self('assetPath') },
        {
          gatewayUrl: ctx.get('hub.gatewayUrl'),
          useAssetTypePathPrefix: ctx.get('gatewayAccess.useAssetTypePathPrefix'),
          deployedEndpoint: ctx.self('deployedEndpoint'),
        },
      );
      const apiKeyHeader = ctx.get('gatewayAccess.subscriptionKeyHeader');
      const city = ctx.self('city');
      const expectedUnit = FAHRENHEIT_CITIES.some((name) => name.toLowerCase() === String(city).toLowerCase())
        ? 'Fahrenheit'
        : 'Celsius';
      return createExecutionPlan({
        sampleId: 'weather-tools-call',
        title: 'Weather tool: direct tools/call',
        summary: 'Open a session, invoke `get-weather`, and check the returned payload.',
        risk: ctx.risk,
        sourceCells: [29],
        steps: [
          mcpInitializeStep({ endpoint, apiKeyHeader, jsonRpcId: 1 }),
          mcpCallStep({
            id: 'tools-call',
            endpoint,
            apiKeyHeader,
            method: 'tools/call',
            params: { name: ctx.self('toolName'), arguments: { city } },
            jsonRpcId: 2,
            title: 'MCP tools/call',
            detail: 'The gateway injects the caller`s key into the source API`s custom header for the internal hop.',
            produces: ['status', 'result', 'content'],
          }),
          step.assertion({
            id: 'assert-weather',
            title: 'Parse the payload and check its shape',
            detail: 'Values are randomised by the mock policy, so presence, type and the unit branch are what is asserted.',
            assertion: {
              kind: 'weather-payload',
              source: '{{steps.tools-call.content}}',
              expectations: [
                '`result.content` is a non-empty array and `content[0].text` parses as JSON.',
                'The payload holds `city`, `temperature`, `temperature_format`, `description`, `humidity` and `wind_speed`.',
                `\`city\` equals "${city}".`,
                `\`temperature_format\` is "${expectedUnit}" for "${city}".`,
                '`temperature` and `wind_speed` are numbers; `humidity` is a number.',
                'Values other than `city` and `temperature_format` are randomised and are not asserted.',
              ],
              expectedFields: ['city', 'temperature', 'temperature_format', 'description', 'humidity', 'wind_speed'],
              expectedUnit,
              fahrenheitCities: FAHRENHEIT_CITIES,
              endpoint,
            },
            produces: ['payload'],
          }),
        ],
        expectedResults: ctx.expectedResults,
        notes: ctx.notes,
        deviations: ctx.deviations,
      });
    },
  },
];
