export const AZURE_REGION_CATALOG = Object.freeze({
  verifiedAt: '2026-09-15',
  sources: Object.freeze([
    'https://learn.microsoft.com/azure/reliability/regions-list',
    'https://learn.microsoft.com/azure/azure-government/documentation-government-welcome#list-of-regions',
    'https://learn.microsoft.com/azure/china/overview-regions',
    'https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/AzureLocation.cs',
  ]),
});

// Offline suggestions, not a subscription or service availability restriction.
export const AZURE_REGION_NAMES = Object.freeze({
  australiacentral: 'Australia Central',
  australiacentral2: 'Australia Central 2',
  australiaeast: 'Australia East',
  australiasoutheast: 'Australia Southeast',
  austriaeast: 'Austria East',
  belgiumcentral: 'Belgium Central',
  brazilsouth: 'Brazil South',
  brazilsoutheast: 'Brazil Southeast',
  canadacentral: 'Canada Central',
  canadaeast: 'Canada East',
  centralindia: 'Central India',
  centralus: 'Central US',
  chilecentral: 'Chile Central',
  chinaeast: 'China East',
  chinaeast2: 'China East 2',
  chinaeast3: 'China East 3',
  chinanorth: 'China North',
  chinanorth2: 'China North 2',
  chinanorth3: 'China North 3',
  denmarkeast: 'Denmark East',
  eastasia: 'East Asia',
  eastus: 'East US',
  eastus2: 'East US 2',
  francecentral: 'France Central',
  francesouth: 'France South',
  germanynorth: 'Germany North',
  germanywestcentral: 'Germany West Central',
  indiasouthcentral: 'India South Central',
  indonesiacentral: 'Indonesia Central',
  israelcentral: 'Israel Central',
  italynorth: 'Italy North',
  japaneast: 'Japan East',
  japanwest: 'Japan West',
  koreacentral: 'Korea Central',
  koreasouth: 'Korea South',
  malaysiawest: 'Malaysia West',
  mexicocentral: 'Mexico Central',
  newzealandnorth: 'New Zealand North',
  northcentralus: 'North Central US',
  northeurope: 'North Europe',
  norwayeast: 'Norway East',
  norwaywest: 'Norway West',
  polandcentral: 'Poland Central',
  qatarcentral: 'Qatar Central',
  southafricanorth: 'South Africa North',
  southafricawest: 'South Africa West',
  southcentralus: 'South Central US',
  southindia: 'South India',
  southeastasia: 'Southeast Asia',
  spaincentral: 'Spain Central',
  swedencentral: 'Sweden Central',
  swedensouth: 'Sweden South',
  switzerlandnorth: 'Switzerland North',
  switzerlandwest: 'Switzerland West',
  uaecentral: 'UAE Central',
  uaenorth: 'UAE North',
  uksouth: 'UK South',
  ukwest: 'UK West',
  usdodcentral: 'US DoD Central',
  usdodeast: 'US DoD East',
  usgovarizona: 'US Gov Arizona',
  usgovtexas: 'US Gov Texas',
  usgovvirginia: 'US Gov Virginia',
  westcentralus: 'West Central US',
  westeurope: 'West Europe',
  westindia: 'West India',
  westus: 'West US',
  westus2: 'West US 2',
  westus3: 'West US 3',
});

export const AZURE_REGIONS = Object.freeze(Object.keys(AZURE_REGION_NAMES));
